"""empty message

Revision ID: 362c94a67619
Revises: d08bdfdbc1b1
Create Date: 2023-03-09 20:44:44.834885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362c94a67619'
down_revision = 'd08bdfdbc1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('pet_name', sa.String(length=250), nullable=True),
    sa.Column('pet_phot', sa.String(length=500), nullable=True),
    sa.Column('pet_fact', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('pet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
